### ISSUE TITLE
 Unexpected token export

### ISSUE THREAD

**Issue by atulsingh589** [xunuoi/node-bigpipe#4]
it gives me 
<code>
SyntaxError: Unexpected token export
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
</code>
this error

**Comment by xunuoi** [comment]
It seems you're not using the es5 version, could you provide your context for for this ?

You need require it in `NodeJS` environment.
If your context doesn't support ES6 syntax, it should like this

```js
var Bigpipe = require('node-bigpipe').Bigpipe

....

```

**Comment by xunuoi** [comment]
Mark as resolved.
